name: MongoDB Memory Server Action
description: Support db-seed testing via an in-memory storage MongoDB instance
author: Neo Financial Engineering
inputs:
  dbConnectionStringEnvVar:
    description: |
      The name of an ENV variable your MongoDB-dependent process will use for the connection string.
      This action will inject this ENV variable into the process space of your runCommand, using the
      instantiated MongoDB server's 'uri' property.
    required: true
  runCommand:
    description: The command that initiates your MongoDB-dependent process.
    required: true
  mongomsDatabaseName:
    description: The DB Name (defaults to a random name).
    required: false
  mongomsPort:
    description: The DB Port (defaults to '27017').
    required: false
  mongomsStorageEngine:
    description: |
      The name of the storage engine to apply (defaults to 'ephemeralForTest'), with the alternate value 'wiredTiger'.
    required: false
  mongomsBinaryVersion:
    description: The version of MongoDB to install (defaults to 4.4.0).
    required: false
  mongomsDebug:
    description: |
      Enables a Debug mode for the in-memory storage MongoDB instance (any value supplied will be taken as 'true').
    required: false
runs:
  using: 'node12'
  main: 'build/index.js'
