name: MongoDB Memory Server Action
description: Support db-seed testing via an in-memory storage MongoDB instance
author: Neo Financial Engineering
inputs:
  db_connection_env_var:
    required: true
    description: |
      The name of an ENV variable your MongoDB-dependent process will use for the connection string.
      This action will inject this ENV variable into the process space of your run_command, using the
      instantiated MongoDB server's 'uri' property.
  db_connection2_env_var:
    required: false
    description: An additional ENV variable (for a secondary connection to the same database instance).
  mongodb_version:
    required: false
    description: If provided, specifies the version of mongod to install.
  run_command:
    required: true
    description: The command that initiates your MongoDB-dependent process.
runs:
  using: 'node12'
  main: 'bin/index.js'
