name: MongoDB Memory Server Action
description: Support db-seed testing via an in-memory storage MongoDB instance
author: Neo Financial Engineering
inputs:
  db_connection_env_var:
    required: true
    description: |
      The name of an ENV variable your MongoDB-dependent process will use for the connection string.
      This action will inject this ENV variable into the process space of your run_command, using the
      instantiated MongoDB server's 'uri' property.
  run_command:
    required: true
    description: The command that initiates your MongoDB-dependent process.
  instance_dbName:
    required: false
    description: The DB Name (defaults to random)
  instance_port:
    required: false
    description: The DB Port (defaults to 27017)
  binary_version:
    required: false
    description: The version of MongoDB to install.
runs:
  using: 'node12'
  main: 'build/index.js'
