name: publish
on:
  push:
    branches: [master, main]
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-22.04
    environment: production
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Get yarn cache
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn --prefer-offline --frozen-lockfile --no-progress --non-interactive
      - name: Build
        run: yarn build
      - name: Package
        run: yarn package
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@e00cb83a68c1158b29afc5217dd0582cada6d172
        with:
          gpg_private_key: ${{ secrets.NEOBOT_GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Commit latest build artifacts
        uses: endbug/add-and-commit@v7
        with:
          author_name: ${{ vars.NEOBOT_AUTHOR }}
          author_email: ${{ vars.NEOBOT_AUTHOR_EMAIL }}
          signoff: true
      - uses: Saionaro/extract-package-version@de8268c348d3a9ed3514c86a9ad8d4568ab8b49e
        id: extract_version
      - uses: mathieudutour/github-tag-action@d745f2e74aaf1ee82e747b181f7a0967978abee0
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.extract_version.outputs.version }}
  coverage:
    runs-on: ubuntu-22.04
    environment: production
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Get yarn cache
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn --prefer-offline --frozen-lockfile --no-progress --non-interactive
      - name: Test
        run: yarn test
      - name: Coverage
        uses: neofinancial/coverage-upload-action@v2
        with:
          coverageEndpoint: ${{ secrets.COVERAGE_ENDPOINT }}
          coverageToken: ${{secrets.COVERAGE_TOKEN}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}