name: test
on:
  push:
    branches-ignore: [ master, main ]
jobs:
  source:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - run: ls -R
      - run: zip -r -y -q ${{ github.sha }}.zip .
      - uses: 'actions/upload-artifact@v2'
        with:
          name: ${{ github.sha }}
          path: ${{ github.sha }}.zip
  download-source:
    runs-on: ubuntu-latest
    needs: [ source ]
    timeout-minutes: 1
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ${{ github.sha }}
      - run: unzip -q -o ${{ github.sha }}.zip -d .
      - run: ls -R
