
name: ticket-check
on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]
jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ticketPrefix: 'CH-'
          titleRegex: '^(CH)(-?)(\d{3,})'
          bodyRegex: '(CH)(-?)(\d{3,})'
          bodyURLRegex: 'http(s?):\/\/(app.clubhouse.io)(\/neofinancial)(\/story)\/\d+'
          exemptUsers: 'renovate, dependabot'
